

export const ErrorCodes = {
  ZOD_VALIDATION_ERROR: "ZOD_VALIDATION_ERROR",
  ZOD_AUTH_VALIDATION_ERROR: "ZOD_AUTH_VALIDATION_ERROR",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  WRONG_AUTH_DATA_ERROR: "WRONG_AUTH_DATA_ERROR"
};